### PR TITLE
feat: Adapt parameters for Ruby 3

### PR DESCRIPTION
**Pull request by jamartinezvillar**
### What is the goal?

Fixing some parameter warnings in functions, which in ruby3 cause errors.

> **tl;dr**
> In Ruby 3.0, positional arguments and keyword arguments will be separated. Ruby 2.7 will warn for behaviours that will change in Ruby 3.0. If you see the following warnings, you need to update your code:
> 
> Using the last argument as keyword parameters is deprecated, or
> Passing the keyword argument as the last hash parameter is deprecated, or
> Splitting the last argument into positional and keyword parameters is deprecated

https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Tipical warning messages in ruby 2.7

```
/app/app/presenters/order_presenter.rb:220: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/bundle/alpine_3.15/2.7.5/ruby/2.7.0/gems/i18n-1.11.0/lib/i18n.rb:210: warning: The called method `t' is defined here
/app/app/presenters/order_log_entry_presenter.rb:238: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/bundle/alpine_3.15/2.7.5/ruby/2.7.0/gems/i18n-1.11.0/lib/i18n.rb:210: warning: The called method `t' is defined here
```
 ### References
10%
pull requests: 
* https://github.com/sequra/simba/pull/5057
* https://github.com/sequra/simba/pull/5083
* https://github.com/sequra/simba/pull/5104
* https://github.com/sequra/simba/pull/5116

 ### How is it being implemented?

Use the explicit call in hash params `**options`

 ### Does the change affect accounting?

No

 ### Does it affect anything sensitive for Findirect?

No

 ### Opportunistic refactorings

This is a refactor

 ### Caveats

No

 ### How is it tested?

Automatic tests

 ### How is it going to be deployed?

Standard deployment

### CODE REVIEW

**Review by bcurtu — APPROVED** [review]
Thank you!
You will need to generate a new release, and update the version file.

**Comment by jgtomas** [comment]
hi @sequra/internationalization any problem to merge this PR? we need this changes to be able to migrate ruby to version 3

**Comment by jaimevelaz** [comment]
@sequra/internationalization @sequra/risk-tech finally found some other deprecations that did not exist when the PR was created. Now all of them are fixed (validated against specs). If everything looks good for you, we can merge this a generate a new version.

**Review by bcurtu — APPROVED** [review]
thank you!

**Pull request merged**
